//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockProgressFile
    {
        public int BlockProgressFileId { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }
        public string FileType { get; set; }
        public int ProgressId { get; set; }
    
        public virtual BlockProgress BlockProgress { get; set; }
    }
}
