//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockProgress()
        {
            this.BlockProgressFiles = new HashSet<BlockProgressFile>();
            this.BlockProgressReviews = new HashSet<BlockProgressReview>();
        }
    
        public int ProgressId { get; set; }
        public int BlockId { get; set; }
        public int PlanId { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public Nullable<System.DateTime> FinalCompletionDate { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual PaymentPlan PaymentPlan { get; set; }
        public virtual ProjectUnitBlock ProjectUnitBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockProgressFile> BlockProgressFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockProgressReview> BlockProgressReviews { get; set; }
    }
}
