//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpDetail
    {
        public int FollowUpId { get; set; }
        public int InquiryId { get; set; }
        public System.DateTime FollowUpDetailsDate { get; set; }
        public int FollowUpById { get; set; }
        public int ModeId { get; set; }
        public string FollowUpRemarks { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public int ResponseTypeId { get; set; }
        public int FollowUpStatusId { get; set; }
    
        public virtual CommunicationMode CommunicationMode { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Inquiry Inquiry { get; set; }
        public virtual ResponseType ResponseType { get; set; }
    }
}
