//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inquiry()
        {
            this.FollowUpDetails = new HashSet<FollowUpDetail>();
        }
    
        public int InquiryId { get; set; }
        public int ProjectId { get; set; }
        public string VisitorName { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string ReferencedBy { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<int> FollowUpBy { get; set; }
        public int Attendee { get; set; }
        public string Remarks { get; set; }
        public Nullable<short> InquiryDay { get; set; }
        public Nullable<short> InquiryMonth { get; set; }
        public Nullable<short> InquiryYear { get; set; }
        public Nullable<short> InquiryWeekNo { get; set; }
        public Nullable<System.DateTime> InquiryStartWeekDate { get; set; }
        public Nullable<System.DateTime> InquiryEndWeekDate { get; set; }
        public int StatusId { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public string Requirement { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowUpDetail> FollowUpDetails { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
    }
}
