//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMaster()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PaymentFiles = new HashSet<PaymentFile>();
        }
    
        public int PaymentMasterId { get; set; }
        public int ProjectId { get; set; }
        public int MemberId { get; set; }
        public int ProjectPropertyId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<int> RBankId { get; set; }
        public string RBranchName { get; set; }
        public string RChequeNo { get; set; }
        public Nullable<System.DateTime> RChequeDate { get; set; }
        public Nullable<decimal> RAmount { get; set; }
        public Nullable<int> GBankId { get; set; }
        public string GBranchName { get; set; }
        public string GChequeNo { get; set; }
        public Nullable<System.DateTime> GChequeDate { get; set; }
        public Nullable<decimal> GAmount { get; set; }
        public Nullable<int> TBankId { get; set; }
        public string TBranchName { get; set; }
        public string TChequeNo { get; set; }
        public Nullable<System.DateTime> TChequeDate { get; set; }
        public Nullable<decimal> TAmount { get; set; }
        public decimal ActualAmount { get; set; }
        public decimal SGSTPer { get; set; }
        public decimal CGSTPer { get; set; }
        public decimal SGSTAmount { get; set; }
        public decimal CGSTAmount { get; set; }
        public decimal FinalAmount { get; set; }
        public string FinalAmountInWords { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int SequenceNo { get; set; }
        public Nullable<int> Month { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsFinalize { get; set; }
        public Nullable<decimal> AplicableGSTAmount { get; set; }
        public Nullable<decimal> AplicableTDSAmount { get; set; }
        public Nullable<decimal> AplicableTotalAmount { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<bool> IsRBankCancelled { get; set; }
        public Nullable<bool> IsGBankCancelled { get; set; }
        public Nullable<bool> IsTBankCancelled { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
        public virtual BankMaster BankMaster1 { get; set; }
        public virtual BankMaster BankMaster2 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentFile> PaymentFiles { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectUnitPropertyDetail ProjectUnitPropertyDetail { get; set; }
    }
}
