//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectPlan()
        {
            this.ProjectFiles = new HashSet<ProjectFile>();
            this.ProjectUnitPropertyDetails = new HashSet<ProjectUnitPropertyDetail>();
        }
    
        public int ProjectPlanId { get; set; }
        public int ProjectId { get; set; }
        public string ProjectPlanName { get; set; }
        public decimal BuildupArea { get; set; }
        public decimal TotalBuildupCarpetArea { get; set; }
        public decimal SaleableArea { get; set; }
        public Nullable<decimal> SaleableCarpetTerraceArea { get; set; }
        public short SaleableAreaUnitId { get; set; }
        public Nullable<short> BuildUpUnitId { get; set; }
        public Nullable<short> BuildUpCarpetUnitId { get; set; }
        public Nullable<short> SaleableCarpetUnitId { get; set; }
        public Nullable<decimal> InsiteCarpetArea { get; set; }
        public Nullable<decimal> BalconyArea { get; set; }
        public Nullable<decimal> WashArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFile> ProjectFiles { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
        public virtual Unit Unit3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectUnitPropertyDetail> ProjectUnitPropertyDetails { get; set; }
    }
}
