//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUnitPropertyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectUnitPropertyDetail()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PaymentMasters = new HashSet<PaymentMaster>();
        }
    
        public int ProjectPropertyId { get; set; }
        public int ProjectId { get; set; }
        public int ProjectUnitId { get; set; }
        public Nullable<int> ProjectRelatedPlanId { get; set; }
        public int PropertyTypeId { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public string FlatNumber { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<decimal> BuidUpArea { get; set; }
        public Nullable<decimal> SalebleAreaFt { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public Nullable<decimal> SalebleAreaYards { get; set; }
        public Nullable<decimal> InsideArea { get; set; }
        public Nullable<decimal> BalconyArea { get; set; }
        public Nullable<decimal> WashArea { get; set; }
        public Nullable<decimal> TotalCarpetArea { get; set; }
        public Nullable<decimal> OpenTerraceAreaFt { get; set; }
        public Nullable<decimal> OpenTerraceAreaYards { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMaster> PaymentMasters { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectPlan ProjectPlan { get; set; }
        public virtual ProjectUnitBlock ProjectUnitBlock { get; set; }
    }
}
