//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFile
    {
        public int FileId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProjectPlanId { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }
        public string FileType { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectPlan ProjectPlan { get; set; }
    }
}
