//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildconConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyType
    {
        public int TypeId { get; set; }
        public string Name { get; set; }
        public int SACCodeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual SACCodeMaster SACCodeMaster { get; set; }
    }
}
