//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildcon_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Mahalaxmi_HandicraftEntities : DbContext
    {
        public Mahalaxmi_HandicraftEntities()
            : base("name=Mahalaxmi_HandicraftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Measurement_unit> Measurement_unit { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Memeber_Category> Memeber_Category { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Product_RM_usage> Product_RM_usage { get; set; }
        public virtual DbSet<Product_Subproduct_relation> Product_Subproduct_relation { get; set; }
        public virtual DbSet<Raw_Material> Raw_Material { get; set; }
        public virtual DbSet<Raw_material_supplier_relation> Raw_material_supplier_relation { get; set; }
        public virtual DbSet<Rawmaterial_Category> Rawmaterial_Category { get; set; }
        public virtual DbSet<Sub_Product> Sub_Product { get; set; }
        public virtual DbSet<Subproduct_RM_usage> Subproduct_RM_usage { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Transaction_details> Transaction_details { get; set; }
        public virtual DbSet<Transaction_History> Transaction_History { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
    
        public virtual ObjectResult<sp_Products_Result> sp_Products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Products_Result>("sp_Products");
        }
    
        public virtual ObjectResult<BindCategory_Result> BindCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindCategory_Result>("BindCategory");
        }
    
        public virtual ObjectResult<BindLocation_Result> BindLocation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BindLocation_Result>("BindLocation");
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_SaveProducts(Nullable<int> productid, string name, string description, Nullable<int> sKU, Nullable<int> categoryid, Nullable<int> locationid, Nullable<int> labourrate)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var sKUParameter = sKU.HasValue ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(int));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("Categoryid", categoryid) :
                new ObjectParameter("Categoryid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var labourrateParameter = labourrate.HasValue ?
                new ObjectParameter("labourrate", labourrate) :
                new ObjectParameter("labourrate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_SaveProducts", productidParameter, nameParameter, descriptionParameter, sKUParameter, categoryidParameter, locationidParameter, labourrateParameter);
        }
    
        public virtual int DeleteProducts(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProducts", idParameter);
        }
    
        public virtual ObjectResult<GetProductRMRelation_Result> GetProductRMRelation(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductRMRelation_Result>("GetProductRMRelation", productidParameter);
        }
    
        public virtual ObjectResult<GetProductRMRelation1_Result> GetProductRMRelation1(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductRMRelation1_Result>("GetProductRMRelation1", productidParameter);
        }
    
        public virtual ObjectResult<sp_RawMaterials_Result> sp_RawMaterials()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RawMaterials_Result>("sp_RawMaterials");
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_SaveProductsRmRelations(Nullable<int> pmrid, Nullable<int> productid, Nullable<int> rMId, Nullable<decimal> requiredQty)
        {
            var pmridParameter = pmrid.HasValue ?
                new ObjectParameter("pmrid", pmrid) :
                new ObjectParameter("pmrid", typeof(int));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("Productid", productid) :
                new ObjectParameter("Productid", typeof(int));
    
            var rMIdParameter = rMId.HasValue ?
                new ObjectParameter("RMId", rMId) :
                new ObjectParameter("RMId", typeof(int));
    
            var requiredQtyParameter = requiredQty.HasValue ?
                new ObjectParameter("RequiredQty", requiredQty) :
                new ObjectParameter("RequiredQty", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_SaveProductsRmRelations", pmridParameter, productidParameter, rMIdParameter, requiredQtyParameter);
        }
    
        public virtual ObjectResult<childmenulist_Result> childmenulist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<childmenulist_Result>("childmenulist");
        }
    
        public virtual ObjectResult<parentmenulist_Result> parentmenulist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<parentmenulist_Result>("parentmenulist");
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_SaveSubProductsRmRelations(Nullable<int> pSR_id, Nullable<int> productid, Nullable<int> subProduct_id, Nullable<decimal> requiredQty)
        {
            var pSR_idParameter = pSR_id.HasValue ?
                new ObjectParameter("PSR_id", pSR_id) :
                new ObjectParameter("PSR_id", typeof(int));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("Productid", productid) :
                new ObjectParameter("Productid", typeof(int));
    
            var subProduct_idParameter = subProduct_id.HasValue ?
                new ObjectParameter("SubProduct_id", subProduct_id) :
                new ObjectParameter("SubProduct_id", typeof(int));
    
            var requiredQtyParameter = requiredQty.HasValue ?
                new ObjectParameter("RequiredQty", requiredQty) :
                new ObjectParameter("RequiredQty", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_SaveSubProductsRmRelations", pSR_idParameter, productidParameter, subProduct_idParameter, requiredQtyParameter);
        }
    
        public virtual ObjectResult<sp_subproduct_Result> sp_subproduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_subproduct_Result>("sp_subproduct");
        }
    
        public virtual ObjectResult<string> DeleteProductsRmRelation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteProductsRmRelation", idParameter);
        }
    
        public virtual ObjectResult<string> DeleteProductsSubproductRelation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("DeleteProductsSubproductRelation", idParameter);
        }
    }
}
