//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildcon_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_id { get; set; }
        public int Member_id { get; set; }
        public int Trx_id { get; set; }
        public int Payment_date { get; set; }
        public int Mode { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
