//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildcon_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Subproduct_relation
    {
        public int PSR_id { get; set; }
        public int Product_id { get; set; }
        public int SubProduct_id { get; set; }
        public decimal Required_qty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sub_Product Sub_Product { get; set; }
    }
}
