//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildcon_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subproduct_RM_usage
    {
        public int SPRM_id { get; set; }
        public int Subproduct_id { get; set; }
        public int Rawmaterial_id { get; set; }
        public decimal Required_qty { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Sub_Product Sub_Product { get; set; }
    }
}
