//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildcon_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Payments = new HashSet<Payment>();
            this.Transaction_History = new HashSet<Transaction_History>();
            this.Transaction_details1 = new HashSet<Transaction_details>();
        }
    
        public int Trx_id { get; set; }
        public int Member_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> subproduct_id { get; set; }
        public int Required_Qty { get; set; }
        public decimal Total_Weight_given { get; set; }
        public Nullable<decimal> Total_weight_recieved { get; set; }
        public Nullable<int> Recieved_qty { get; set; }
        public System.DateTime Order_datte { get; set; }
        public System.DateTime Return_date { get; set; }
        public Nullable<System.DateTime> Actual_return_date { get; set; }
        public System.DateTime Valid_From { get; set; }
        public System.DateTime Valide_to { get; set; }
        public bool Is_completed { get; set; }
        public decimal Calculated_Piece_Labor_Rate { get; set; }
        public decimal Actual_piece_labor_rate { get; set; }
        public decimal Total_Actual_Amount { get; set; }
        public System.DateTime Order_date { get; set; }
        public decimal Piece_Labor_Rate { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Product Product { get; set; }
        public virtual Transaction_details Transaction_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_History> Transaction_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_details> Transaction_details1 { get; set; }
    }
}
