//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaligramBuildcon_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_details
    {
        public int Trxdetails_id { get; set; }
        public int Trx_id { get; set; }
        public int Rawmaterial_id { get; set; }
        public int subproduct_id { get; set; }
        public decimal Required_qty { get; set; }
        public decimal Given_qty { get; set; }
        public bool Is_pending { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime Updated_at { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Sub_Product Sub_Product { get; set; }
        public virtual Transaction Transaction { get; set; }
        public virtual Transaction Transaction1 { get; set; }
    }
}
